name: Hello OCR Example Minimal Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ["make run_cli", "python filter_hello_ocr/main_minimal_script.py"]
    defaults:
      run:
        shell: bash
        working-directory: ./examples/hello-ocr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run:
          make install
      - name: Run command
        run:
          ${{ matrix.command }}