name: Minimal CLI pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./examples/hello-ocr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run:
          make install
      - name: Run openfilter using CLI
        run:
          make run_cli